// ============================================================
// ClinicGo — Mock Data
// Loaded as a plain <script> before any React components.
// All values are attached to window so every component file
// can read them without ES-module imports.
// ============================================================

window.DOCTORS = [
  {
    id: 1,
    name: 'Dr. Ahmed El-Sayed',
    specialty: 'Cardiologist',
    rating: 4.9,
    reviews: 312,
    location: 'Maadi, Cairo',
    fee: 350,
    nextSlot: 'Today, 3:00 PM',
    verified: true,
    image: 'https://randomuser.me/api/portraits/men/32.jpg',
    experience: 15,
    languages: ['Arabic', 'English'],
    about: 'Dr. Ahmed El-Sayed is a highly experienced cardiologist with over 15 years in cardiovascular medicine. He specialises in heart failure, coronary artery disease, and preventive cardiology.',
    availability: ['Sun', 'Mon', 'Tue', 'Thu'],
    timeSlots: ['9:00 AM', '9:30 AM', '10:00 AM', '11:00 AM', '2:00 PM', '3:00 PM', '4:30 PM'],
  },
  {
    id: 2,
    name: 'Dr. Sara Mansour',
    specialty: 'Dermatologist',
    rating: 4.8,
    reviews: 256,
    location: 'Zamalek, Cairo',
    fee: 400,
    nextSlot: 'Today, 5:00 PM',
    verified: true,
    image: 'https://randomuser.me/api/portraits/women/44.jpg',
    experience: 10,
    languages: ['Arabic', 'English', 'French'],
    about: 'Dr. Sara Mansour is a renowned dermatologist specialising in cosmetic dermatology, acne treatment, and skin cancer screening. She brings a gentle, patient-centred approach to every consultation.',
    availability: ['Mon', 'Wed', 'Thu', 'Sat'],
    timeSlots: ['10:00 AM', '11:00 AM', '12:00 PM', '2:30 PM', '4:00 PM', '5:00 PM'],
  },
  {
    id: 3,
    name: 'Dr. Khaled Ibrahim',
    specialty: 'Pediatrician',
    rating: 4.9,
    reviews: 489,
    location: 'Heliopolis, Cairo',
    fee: 250,
    nextSlot: 'Tomorrow, 10:00 AM',
    verified: true,
    image: 'https://randomuser.me/api/portraits/men/45.jpg',
    experience: 18,
    languages: ['Arabic', 'English'],
    about: 'Dr. Khaled Ibrahim is a beloved pediatrician with 18 years of experience caring for children from newborns to adolescents. Known for his warm manner and comprehensive approach to child health.',
    availability: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu'],
    timeSlots: ['8:00 AM', '8:30 AM', '9:00 AM', '10:00 AM', '11:00 AM', '12:00 PM'],
  },
  {
    id: 4,
    name: 'Dr. Nadia Farouk',
    specialty: 'Gynecologist',
    rating: 4.7,
    reviews: 203,
    location: 'Smouha, Alexandria',
    fee: 300,
    nextSlot: 'Today, 2:00 PM',
    verified: true,
    image: 'https://randomuser.me/api/portraits/women/68.jpg',
    experience: 12,
    languages: ['Arabic', 'English'],
    about: "Dr. Nadia Farouk is a dedicated gynecologist specialising in women's health, maternal care, and minimally invasive surgery. She is committed to providing compassionate, evidence-based care.",
    availability: ['Mon', 'Tue', 'Thu', 'Sat'],
    timeSlots: ['9:00 AM', '10:30 AM', '12:00 PM', '2:00 PM', '3:30 PM'],
  },
  {
    id: 5,
    name: 'Dr. Tarek Hassan',
    specialty: 'Orthopedic',
    rating: 4.8,
    reviews: 178,
    location: 'Mohandessin, Cairo',
    fee: 450,
    nextSlot: 'Tomorrow, 11:00 AM',
    verified: false,
    image: 'https://randomuser.me/api/portraits/men/22.jpg',
    experience: 20,
    languages: ['Arabic', 'English'],
    about: 'Dr. Tarek Hassan is an orthopedic surgeon with expertise in joint replacement, sports injuries, and spinal disorders. He has performed over 2,000 successful surgeries.',
    availability: ['Sun', 'Wed', 'Thu'],
    timeSlots: ['10:00 AM', '11:00 AM', '12:00 PM', '3:00 PM', '4:00 PM'],
  },
  {
    id: 6,
    name: 'Dr. Layla Mostafa',
    specialty: 'Neurologist',
    rating: 4.9,
    reviews: 267,
    location: 'Gleem, Alexandria',
    fee: 500,
    nextSlot: 'Today, 6:00 PM',
    verified: true,
    image: 'https://randomuser.me/api/portraits/women/26.jpg',
    experience: 14,
    languages: ['Arabic', 'English', 'German'],
    about: 'Dr. Layla Mostafa is a distinguished neurologist specialising in epilepsy, migraines, and neurodegenerative diseases. She combines research with personalised patient care.',
    availability: ['Mon', 'Tue', 'Thu', 'Fri'],
    timeSlots: ['11:00 AM', '12:00 PM', '2:00 PM', '4:00 PM', '5:00 PM', '6:00 PM'],
  },
  {
    id: 7,
    name: 'Dr. Omar Galal',
    specialty: 'ENT',
    rating: 4.6,
    reviews: 134,
    location: 'Nasr City, Cairo',
    fee: 280,
    nextSlot: 'Tomorrow, 9:00 AM',
    verified: true,
    image: 'https://randomuser.me/api/portraits/men/36.jpg',
    experience: 9,
    languages: ['Arabic', 'English'],
    about: 'Dr. Omar Galal is an ENT specialist with expertise in sinusitis, hearing loss, and throat conditions. He offers both medical and surgical management using the latest endoscopic techniques.',
    availability: ['Sun', 'Mon', 'Wed', 'Thu'],
    timeSlots: ['9:00 AM', '9:30 AM', '10:00 AM', '11:30 AM', '2:00 PM', '3:00 PM'],
  },
  {
    id: 8,
    name: 'Dr. Rana Soliman',
    specialty: 'Ophthalmologist',
    rating: 4.8,
    reviews: 198,
    location: 'Dokki, Cairo',
    fee: 350,
    nextSlot: 'Today, 4:00 PM',
    verified: true,
    image: 'https://randomuser.me/api/portraits/women/12.jpg',
    experience: 11,
    languages: ['Arabic', 'English'],
    about: "Dr. Rana Soliman is a skilled ophthalmologist specialising in cataract surgery, refractive errors, and glaucoma management. She is dedicated to preserving her patients' vision.",
    availability: ['Mon', 'Tue', 'Wed', 'Thu', 'Sat'],
    timeSlots: ['10:00 AM', '11:00 AM', '1:00 PM', '2:00 PM', '3:00 PM', '4:00 PM'],
  },
  {
    id: 9,
    name: 'Dr. Hossam Nabil',
    specialty: 'Cardiologist',
    rating: 4.7,
    reviews: 145,
    location: 'New Cairo, Cairo',
    fee: 400,
    nextSlot: 'Tomorrow, 2:00 PM',
    verified: false,
    image: 'https://randomuser.me/api/portraits/men/55.jpg',
    experience: 13,
    languages: ['Arabic', 'English'],
    about: 'Dr. Hossam Nabil is a cardiologist focused on interventional cardiology and echocardiography, trained at leading cardiac centres in Europe.',
    availability: ['Tue', 'Thu', 'Sat'],
    timeSlots: ['9:00 AM', '10:00 AM', '11:30 AM', '2:00 PM', '3:00 PM'],
  },
  {
    id: 10,
    name: 'Dr. Yasmin Kamal',
    specialty: 'Dermatologist',
    rating: 4.9,
    reviews: 321,
    location: 'Stanley, Alexandria',
    fee: 380,
    nextSlot: 'Today, 7:00 PM',
    verified: true,
    image: 'https://randomuser.me/api/portraits/women/55.jpg',
    experience: 8,
    languages: ['Arabic', 'English', 'French'],
    about: 'Dr. Yasmin Kamal specialises in laser treatments, anti-aging procedures, and chronic skin conditions. She stays at the forefront of dermatological innovation.',
    availability: ['Sun', 'Mon', 'Wed', 'Thu', 'Sat'],
    timeSlots: ['12:00 PM', '1:00 PM', '2:30 PM', '4:00 PM', '5:30 PM', '7:00 PM'],
  },
  {
    id: 11,
    name: 'Dr. Amr Zaki',
    specialty: 'Orthopedic',
    rating: 4.6,
    reviews: 167,
    location: 'Smouha, Alexandria',
    fee: 420,
    nextSlot: 'Tomorrow, 1:00 PM',
    verified: true,
    image: 'https://randomuser.me/api/portraits/men/67.jpg',
    experience: 16,
    languages: ['Arabic', 'English'],
    about: 'Dr. Amr Zaki specialises in sports medicine and arthroscopic surgery. He has worked with professional athletes, helping them recover and return to peak performance.',
    availability: ['Mon', 'Wed', 'Sat'],
    timeSlots: ['10:00 AM', '11:00 AM', '12:00 PM', '1:00 PM', '3:00 PM'],
  },
  {
    id: 12,
    name: 'Dr. Mona Abdallah',
    specialty: 'Pediatrician',
    rating: 4.8,
    reviews: 412,
    location: 'Heliopolis, Cairo',
    fee: 220,
    nextSlot: 'Today, 5:30 PM',
    verified: true,
    image: 'https://randomuser.me/api/portraits/women/82.jpg',
    experience: 20,
    languages: ['Arabic', 'English'],
    about: 'Dr. Mona Abdallah is a senior pediatrician with two decades of experience. She is passionate about early childhood development, vaccination programmes, and childhood chronic disease management.',
    availability: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Sat'],
    timeSlots: ['9:00 AM', '10:00 AM', '11:00 AM', '3:00 PM', '4:30 PM', '5:30 PM'],
  },
];

window.SPECIALTY_OPTIONS = [
  'All Specialties',
  'Cardiologist',
  'Dermatologist',
  'Pediatrician',
  'Orthopedic',
  'Neurologist',
  'Gynecologist',
  'ENT',
  'Ophthalmologist',
];

window.LOCATION_OPTIONS = [
  'All Locations',
  'Cairo',
  'Alexandria',
  'Maadi, Cairo',
  'Zamalek, Cairo',
  'Heliopolis, Cairo',
  'Nasr City, Cairo',
  'Mohandessin, Cairo',
  'New Cairo, Cairo',
  'Dokki, Cairo',
  'Smouha, Alexandria',
  'Gleem, Alexandria',
  'Stanley, Alexandria',
];

// Maps specialty card names (Home page) → doctor specialty labels
window.SPECIALTY_MAP = {
  'Cardiology':    'Cardiologist',
  'Dermatology':   'Dermatologist',
  'Pediatrics':    'Pediatrician',
  'Orthopedics':   'Orthopedic',
  'Neurology':     'Neurologist',
  'Gynecology':    'Gynecologist',
  'ENT':           'ENT',
  'Ophthalmology': 'Ophthalmologist',
};
